### ISSUE TITLE
Add support for absolute paths in `envFileName`

### ISSUE THREAD

**Issue by ruurtjan** [Philippus/sbt-dotenv#137]
Sbt-dotenv currently always prepends the `envFileName` with the base directory.
https://github.com/Philippus/sbt-dotenv/blob/ab634f702fc80ac438f9678f738487a244da15e4/src/main/scala/au/com/onegeek/sbtdotenv/SbtDotenv.scala#L89

I think it would make sense to check if the first character of `envFileName` is a `/`, and if so, don't prepend the base directory.

The use case for me would be to inject an envfile in GitLab CI. It allows you to define environment specific files, and provides an absolute path to these files in an environment variable. It would be convenient to be able to plug that into sbt cli like so:
`sbt "set ThisBuild  / envFileName := \"$SBT_DOT_ENV\"" test`

Would you accept a PR for this?

**Comment by Philippus** [comment]
Sure, sounds like a welcome addition.

**Comment by Philippus** [comment]
Fixed in https://github.com/Philippus/sbt-dotenv/pull/139.
